apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: exchange-service
  namespace: dev
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/dev/exchange-service
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-exchange
                  key: database-password
          envFrom:
            - configMapRef:
                name: exchange-config
